version: "3.8"

services:
  surge-postgres:
    image: postgres:15
    container_name: surge-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: surge_development
    ports:
      - "6432:6432" # 외부 접근 가능하도록 변경
    volumes:
      - surge-postgres-data:/var/lib/postgresql/data # 올바른 데이터 경로
    networks:
      - surge-network
    restart: unless-stopped # 자동 재시작

  surge-core:
    container_name: surge-core
    build:
      context: ./
      dockerfile: development.Dockerfile
    env_file:
      - .env
      - .env.docker
    command: ["./surge"] # 실행 명령 수정
    networks:
      - surge-network
    ports:
      - "7578:7578" # 외부 접근 가능하도록 변경
    depends_on:
      - surge-postgres # Postgres가 먼저 실행되도록 설정
    restart: unless-stopped # 자동 재시작

volumes:
  surge-postgres-data:

networks:
  surge-network:
    driver: bridge
